### ISSUE TITLE
Enphase - Lokales Token läuft ab

### ISSUE THREAD

**Issue by olikra** [TobiasNeuschulz/EVCC-Enphase#1]
Hi,

wir haben hier eine enphase-Anlage und ab Juni 2024 ein E-Auto. Deine Hinweise werden sicherlich helfen, EVCC und Enphase zu integrieren. Vorab vielen Dank.

Nun lese ich bereits über die lokale API alle 15 Minuten Werte aus dem Gateway aus. Das hat auch 6 Monate wunderbar funktioniert. Seit ca. 2 Wochen "expired" das Token aber immer wieder.

Hast Du ein ähnliches Verhalten beobachten können?

Gruss
Oliver

**Comment by TobiasNeuschulz** [comment]
Hast du einen Installer Account verwendet für die Erstellung des Token?

"NOTE: Tokens are valid for a finite time.
• If the user is a system owner, the token is valid for 1 year.
• If the user is an installer, the token is valid for 12 hours."

https://enphase.com/download/iq-gateway-access-using-local-apis-or-local-ui-token-based-authentication-tech-brief

**Comment by olikra** [comment]
In allen Fällen  als System-Owner (meine Schwester) generiert. Enphase Support hatte mir vor zwei Tagen ein Token per Mail (!!!!!!) geschickt. Das hielt aber nur 6 Stunden.

**Comment by TobiasNeuschulz** [comment]
War dann bestimmt ein Installer Token.

Ich selbst habe nur System Owner Berechtigungen und bisher läuft das Token nicht ab. Ich habe letzte Woche eine weitere evcc Installation mit enphase in Betrieb genommen und bisher läuft diese auch.

Ich mutmaße jetzt mal ein wenig: Kannst du mit deinem Account von enphase die App "Toolkit" verwenden? Die ist nämlich für Installateure vorgesehen und mein System Owner kommt da nicht ran. Falls ja - hast du vielleicht bei enphase eine Erweiterung der Rechte angefragt oder die Anlage selbst gebaut? Vielleicht musst du die Accounts für Installateur und System Owner trennen. Aber alles nur Vermutungen.
