### ISSUE TITLE
Live Status - nicht mehr notwendig?

### ISSUE THREAD

**Issue by Soph** [TobiasNeuschulz/EVCC-Enphase#2]
Danke erstmal für die Config 💟 

Ich habe das gerade aufgesetzt und bin die Doku von oben nach unten durchgegangen. Die Werte für die Batterie kamen dann direkt ohne das ich vorher in der App war und den Live Status dadurch aktiviert hätte. Ich hab den cronjob jetzt auch nicht aktiviert und seit > 2h bekommt evcc alle Werte. Eventuell hat Enphase hier in einem der letzten Updates etwas geändert?

Nur zur info und eventuell zum ausprobieren ob das irgendwie an dem Setup hier liegt oder generell besser funktioniert.

**Comment by Soph** [comment]
ok, es ging zwar länger als 15min, aber jetzt hat es doch einen refresh per cronjob gebraucht.

**Comment by TobiasNeuschulz** [comment]
Hi, das Phänomen kenne ich. Wird der LiveStatus per Shell gesetzt ist er deutlich länger aktiv (1-2 Tage habe ich schon beobachtet) und das Skript kaum notwendig. Erst wenn ich mal wieder in der Enphase Enlighten App den Live Status aktiviere, ist er nach 15 min wieder aus. Die App scheint den Timer anders zu "triggern".

Ansonten habe ich nochmal die Doku angepasst. Für den SOC nutze ich jetzt die andere API (/ivp/ensemble/inventory). Dann ist zumindestens der SOC Wert in evcc immer aktuell und unabhängig vom Live Status und dem Skript. Das lasse ich ja nur laufen, wenn auch ein Auto angeschlossen ist.
